### ISSUE TITLE
The SPLIT_COERCION algorithm needs some love.

### ISSUE THREAD

**Issue by favonia** [RedPRL/redtt#132]
The algorithm seems to be correct but would trigger some bizarre error message in `univalence.red`.

**Comment by favonia** [comment]
Practically blocked by RedPRL/algaett#25.

**Comment by favonia** [comment]
This algorithm is wrong because the Part III algorithm does not work in the open-term setting.

**Comment by jonsterling** [comment]
@favonia Fascinating! I look forward to hearing more about it.
