### ISSUE TITLE
Mortal spaces in pretty printing

### ISSUE THREAD

**Issue by favonia** [RedPRL/redtt#156]
There are some strange spaces that I could not understand in the printed expressions.

**Comment by jonsterling** [comment]
yes, I noticed this too. I guess I messed it up.

**Comment by jonsterling** [comment]
I looked into this a little bit and I really couldn't figure out what is happening. I'm just puzzled.

**Comment by favonia** [comment]
I think one instance is that the two spaces before and after an empty list will not collapse into one.
