### ISSUE TITLE
Allow fancy syntax (m n o : nat) -> blah?

### ISSUE THREAD

**Issue by favonia** [RedPRL/redtt#158]

**Comment by favonia** [comment]
@jonsterling This is supported now but with commas. Is there a reason to require the commas?

**Comment by jonsterling** [comment]
@favonia I want to get rid of commas, but I was getting owned by the grammar ambiguities...

**Comment by jonsterling** [comment]
I guess we need to rearrange some parts of the grammar somehow. Another thing I don't like is that it was necessary to write `(Foo bar baz) -> Bingo` instead of `Foo bar baz -> Bingo`. It seems like maybe we need more levels of terms, than just `atomic` and other?

How is this usually dealt with?

**Comment by favonia** [comment]
I wonder if precedence would help...?

**Comment by jonsterling** [comment]
@favonia Yes, it seems like it should somehow, but I personally don't have a good intuition for how it works at the moment.
