### ISSUE TITLE
Elaboration for fix, dfix, etc.

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/redtt#189]
We need high-level constructs for guarded fixed points. The primitive operator is `(dfix r A [x] (F x))`, and this produces `|> A`, but from the point of view of programming, we probably want to instead provide a family of tactics for working with this. In particular:

- `dfix-line x : A in F x` should produce `Line (|> A)`, elaborating to `(lam <i> (dfix i A [x] (F x)))`
- `fix-line x : A in F x` should produce `Line A`, elaborating to `(lam <i> (F (dfix i A [x] (F x))))`
- `dfix x : A in F x` should produce `|> A`, and is equivelent to `(dfix-line x : A in F x) 0`
- `fix x : A in F x` should produce `A` and is eqivalent to `F (dfix x : A in F x)`

If anyone has any better ideas for names than `-line`, I'm all ears.

**Comment by favonia** [comment]
What does `d` stand for?

**Comment by jonsterling** [comment]
@favonia It stands for 'delayed'; the idea is that the `dfix` combinator returns something under the later modality.
