### ISSUE TITLE
design Immortal Notation for datatype declarations

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/redtt#204]
We need a notation that makes sense, and is still explicit about the difference between non-recursive arguments, recursive arguments, dimension arguments, boundaries, etc. It's so brutal!!!

Any ideas would be welcome.

**Comment by favonia** [comment]
Like this? Not sure if it's easily parsable.
```
glue (i : dim) (c : C) with i = 0 => left (f c) | i = 1 => right (g c) end
fill : (i : dim) (x y : self) with i = 0 => x | i = 1 => y end
```

**Comment by jonsterling** [comment]
It's not too bad... We still need to distinguish (for now) between recursive and non-recursive arguments, and with my current Thought, I'm thinking about putting the former in square brackets and the latter in parens. Rather than `self`, I'm using a parsing trick to let you use the name of the type you are defining (just to be a bit less brutal, though personally I feel that `self` is fine).

As for the dimensions, maybe these should go after all the arguments? What do you think?

**Comment by favonia** [comment]
@jonsterling Okay. As for dimensions, I believe they do not have to (and this will be an extension not included in Part IV). I believe the only important thing is that dimension variables in boundaries must be bound.
