### ISSUE TITLE
Z is a set 

### ISSUE THREAD

**Issue by mortberg** [RedPRL/redtt#207]
When trying out my problem we will need a proof that the integers form a set.  We can either prove this directly using J or using Hedberg. Having both proofs could be interesting just to compare for efficiency.

For proofs in cubicaltt/hcomptrans see setZ' (using J) and ZSet (using Hedberg) in: https://github.com/mortberg/cubicaltt/blob/pi4s3/examples/brunerie2.ctt

**Comment by ecavallo** [comment]
I'll give this a shot.

**Comment by ecavallo** [comment]
@jonsterling I've coded up a proof using Hedberg, shall I wait on #230 or...?

**Comment by jonsterling** [comment]
@ecavallo Oh cool!!! Can you commit the proof directly to the Rectification Campaign branch? I will merge soon, but I just want to clean up a few minor things.

**Comment by jonsterling** [comment]
@ecavallo OK, I ended up merging that branch, so feel free to put your code on a new branch, based on `master`.
