### ISSUE TITLE
variable trouble with iterated elim

### ISSUE THREAD

**Issue by ecavallo** [RedPRL/redtt#215]
```
import path
import nat

data unit where
| triv

let Mystery (m : nat) : (n : nat) -> (Path nat m n) -> unit =
  elim m [
  | zero => lam n p -> triv
  | suc m' => lam n -> 
    elim n [
    | zero => lam p -> triv
    | suc n' => lam p -> triv
    ]
  ]
```
raises `Failed to find: m'`. The bug disappears if `Path nat m n` is replaced with something which doesn't depend either on `m` or `n`.

**Comment by jonsterling** [comment]
@ecavallo thanks for catching this. Part of what is happening is that the unifier can't infer the motive in this case, but that is the wrong error for it to raise, so this indicates a bug somewhere. I'll try to track it down.

**Comment by jonsterling** [comment]
I think this is at least partly name resolution issue: that is, a name `m'` is being resolved as the wrong variable somehow.

**Comment by jonsterling** [comment]
lmao, I think I know what the problem is now. I will try to fix it today.
