### ISSUE TITLE
Evaluator too slow

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/redtt#216]
It takes almost a second to normalize the 5th winding number; we can't blame this on the Kan operations, because this is almost instantaneous in yacctt. I think it means we need to revisit some things, and maybe use a completely different style of dimension substitution.

@favonia

**Comment by favonia** [comment]
Hmm, maybe we can try to provide some unsafe operations in `IAbs` (for example `unsafeBind`)? The idea is to minimize unnecessary refreshing.

**Comment by ecavallo** [comment]
`five` is actually 4, btw. The real 5 takes almost 12s!

**Comment by favonia** [comment]
Sorry, I can't count. Maybe I was brainwashed to believe that natural numbers start at `one`.

**Comment by jonsterling** [comment]
@favonia That might help a little bit. To try it out, I tried turning off freshening completely; it breaks many examples of course, but I was able to run the winding number (five or four, lol), and it shaved off around `.25` seconds from it. So IMO it is still extremely slow (we should try to make it instantaneous), but such a performance improvement is significant.

**Comment by mortberg** [comment]
Wow, 12s is surprisingly slow. And fascinating that freshening didn't affect it much either. Can you profile the code to pinpoint where it is slow?

**Comment by jonsterling** [comment]
For what it's worth, this is the profile of an execution with the real `5`:

https://gist.github.com/jonsterling/2945940f555a37cc9349e79def330647

I'm not exactly sure how to interpret it; for instance, that tally of seconds in the profile doesn't reach the total running time of the program, so I found it confusing. Maybe @favonia and @ecavallo can help interpret this data...
