### ISSUE TITLE
Vim editor mode

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/redtt#220]
Let's port the RedPRL vim mode to start with! I'm adding source positions to the output, so it should be possible to reuse a lot of it.

**Comment by jonsterling** [comment]
@cangiuli I started hacking on this and it almost kind of works, but for some reason it nukes my main buffer whenever I call the command to run redtt. LOL. I guess I'll leave it for someone who really knows how to Get Down with vim.

**Comment by cangiuli** [comment]
Is there broken code somewhere for me to look at, or is it better to just scrap it?

**Comment by jonsterling** [comment]
I'll dump my broken code into a branch

**Comment by cangiuli** [comment]
We should either close or rename this. @jonsterling ?
