### ISSUE TITLE
Find a way to limit the pain of restriction pretypes (or remove them)

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/redtt#231]
The restriction pretypes are brutal, and a lot of things are broken because of them. I would like to find a way to remove them, or at least limit their influence. Let me start by recalling why they exist in the first place: we need to be able to have a goal with a restriction, and then skolemize that goal as some kind of type (or other structure) that can be made into a hole in the global context.

Unfortunately they make the implementation very complicated, and in practice really unreliable and confusing. In most places, we are either too clever wrt restrictions or not clever enough.

I would like to remove them and instead make restrictions part of the *judgments*. Stratifying things in this way would clarify a LOT. I don't yet see how to remove the restriction pretypes entirely without making holes impossible (there is probably a way), but to start, I think we could try and implement this judgmental structure.

/cc @ecavallo

**Comment by jonsterling** [comment]
Another thing is that if we use judgmental structure for these in the main (and only internalize them as pretypes when actually necessary, such as skolemizing a goal) it would be more clear how to give an explicit introduction and elimination form to the restriction type, and avoid the question of subtyping between a restriction type and a non-restriction type entirely.

**Comment by favonia** [comment]
Yes, please.

**Comment by favonia** [comment]
Yes! It is weird that restriction types are not internalizing something judgmental!

**Comment by jonsterling** [comment]
@favonia 
> Yes! It is weird that restriction types are not internalizing something judgmental!

Indeed! I think that general principle, that types should internalize judgments, is yet another Law of Eliminating Mortality...
