### ISSUE TITLE
variables getting reversed in HITs

### ISSUE THREAD

**Issue by ecavallo** [RedPRL/redtt#234]
```
data O where
| obase 
| oloop (y : O) @ i
  [ i=0 ⇒ y
  | i=1 ⇒ y
  ]
```
raises `Failure("check_dim_cmd: expected dimension")`, but
```
data O where
| obase 
| oloop (y : O) @ i
  [ y=0 ⇒ i
  | y=1 ⇒ i
  ]
```
typechecks. I've failed to figure out what needs to be switched around to fix it :(

**Comment by jonsterling** [comment]
oops! This doesn't surprise me, I have to guess every time I do anything that involves lists and reversing...

**Comment by jonsterling** [comment]
@ecavallo the problem seems to be in the definition of `psi` in `elab_constr`; but depending on which way I make it go, either the torus doesn't work or your example doesn't work. LOL.

**Comment by ecavallo** [comment]
I had the same experience flipping around `xs` in `bind_in_scope`... I bet there is a bug in the elim code also and they're canceling each other out.

**Comment by jonsterling** [comment]
@ecavallo I think you're right, lmao. Yeah, there's probably `n` times stupid things are getting flipped, and it cancels out. This is my hell... :laughing: 

Anything you can change to make this code less fucked is welcome :sunglasses:

**Comment by jonsterling** [comment]
Let me just suggest that the `in_scope` thing should really have the `rec_specs` first and then `dim_specs`. I think. And the rest of the code should be fixed in order to make that work.

**Comment by jonsterling** [comment]
other potentially problematic spots are `boundary_resolve_name`

**Comment by jonsterling** [comment]
@ecavallo I've pushed a tentative fix in #230

**Comment by jonsterling** [comment]
@ecavallo The second part sounds like progress... What a mess!

**Comment by jonsterling** [comment]
Doing all this binding structure by hand is such a catastrophe, lol.

**Comment by jonsterling** [comment]
@ecavallo OK, I've fixed a number of things (but not enough yet), but let me challenge you with a question: Given the following datatype, what should its elimination rule be?

```
data O where
| obase 
| oloop (y : O) @ i
  [ i=0 ⇒ y
  | i=1 ⇒ y
  ]
```

In particular, I can't even see how to *write down* the restriction for the `oloop` clause.

**Comment by jonsterling** [comment]
Ohh, I think I might see how to do it, it's different than the naive thing I did.

**Comment by jonsterling** [comment]
lmao I am so dumb.

**Comment by ecavallo** [comment]
For the clause `oloop (o' ⇒ result/o') i ⇒ ?` the hole should restrict to `result/o'` on `i=0` and `i=1`.

**Comment by favonia** [comment]
I wonder if this could be avoided if we give reversed lists different types and completely ban `List.rev`.

**Comment by jonsterling** [comment]
For instance, the interface of `Domain.Env` needs to be rectified so that people like me don't get confused when using it.

**Comment by jonsterling** [comment]
It's represented using lists `'a list`, but it should be `'a bwd` internally; and words like `push` are used, when instead `snoc` or `extend` or something should be used. The mental image produced should be of taking a bunch of cells and just putting them at the *end* of the environment, and things are projected from the environment by counting right-to-left, like on paper.
