### ISSUE TITLE
some kind of binding trouble

### ISSUE THREAD

**Issue by ecavallo** [RedPRL/redtt#236]
Just by adding another dimension variable (`w`) to a connection, I get `Failure("rigid-rigid mismatch")`:
```
let connection/and/more
 (A : type)
 (p : dim → A)
 : [i j w] A [
   | j=0 ⇒ p 0
   | i=0 ⇒ p 0
   | j=1 ⇒ p i
   | i=1 ⇒ p j
   ]
 =
 λ i j w →
   let face : dim → dim → A =
     λ l k →
       comp 1 l (p k) [
       | k=0 ⇒ λ _ → p 0
       | k=1 ⇒ p
       ]
   in
   comp 0 1 (p 0) [
   | i=0 ⇒ face 0
   | i=1 ⇒ face j
   | j=0 ⇒ face 0
   | j=1 ⇒ face i
   | i=j ⇒ face i
   ]
```
(You can delete all but one of the faces in the type and definition and get the same result.)

**Comment by ecavallo** [comment]
Ok, this is just that the notation for extension types binds variables in the opposite direction of what I expected.

**Comment by jonsterling** [comment]
@ecavallo It's very possible that I got something backwards... I'm generally very unable to think clearly about n-ary things. Can you describe what you expected and how this differed?

**Comment by jonsterling** [comment]
@ecavallo OK, I'll leave it up to you! Let me provide just a bit of guidance on choosing the right order (and you can determine which order satisfies it):

Application for n-ary line type should work the same as application for iterated 1-ary line type. So, whatever `p r s t` means for `[i j k] A []`, then this must mean the same as it would mean for `[i] ([j] ([k] A []) []) []`.

**Comment by ecavallo** [comment]
Ok, then I will change it.

**Comment by jonsterling** [comment]
@ecavallo OK great, thanks! :fireworks: 

My suggestion is either to commit it to the Rectification Campaign branch, or we should merge that first. I have no preference for which we do.

**Comment by ecavallo** [comment]
Hm, now I don't know what I was talking about yesterday, because I still get (different) `rigid-rigid mismatch`es on this code no matter how I permute either of the `i j w`'s... guess there must be an inconsistency in how they are dealt with somewhere. I'll keep digging.

**Comment by ecavallo** [comment]
Here's a more minimal example which breaks:
```
let test (A : type) (a : A)
  : [i j] A [i=0 ⇒ a | i=1 ⇒ a] =
  λ i j →
  comp 0 1 a [
  | i=0 ⇒ λ _ → a
  | i=1 ⇒ λ _ → a
  ] 
```
I think I was wrong about this having anything to do with variable order... if I flip the `i j`, I get the error message I would expect for the wrong order, while this code raises
```
Encountered error:
    a
    ≠
    (nhcom-type 0 1 A ((up (up (U kan 0) A []) a []))<[0/i]>
     [?j=0 <%51> ((up (up (U kan 0) A []) a []))<%49 <-> %51 ∘ [0/j] ∘ [0/i] ∘ [%49/_] ∘ [0/j]>]
     [?j=1 <%54> ((up (up (U kan 0) A []) a []))<%52 <-> %54 ∘ [1/j] ∘ [0/i] ∘ [%52/_] ∘ [1/j]>])
```
(not sure what that means)

**Comment by jonsterling** [comment]
@ecavallo In advance of me studying this example, can you say whether or not you think that the current order of variables in the extension type binder (or application) is currently correct?

**Comment by ecavallo** [comment]
Yes, I think so.

**Comment by jonsterling** [comment]
thanks! I can try and see what's going on here. That error message looks very familiar to me, lol.

**Comment by jonsterling** [comment]
@ecavallo Here's a simpler version that is broken:

```
let test (A : type) (a : A) : [i j] A [i=0 ⇒ a] =
  ?
```

**Comment by jonsterling** [comment]
This is definitely an issue where something (or multiple things) are backwards.

**Comment by jonsterling** [comment]
The problems actually reach down all the way into the parser, resolver, pretty printer. There were a lot of things that are mutually reversed (LOL). I think i see what needs to be done.

**Comment by jonsterling** [comment]
done, i think: #242
