### ISSUE TITLE
[domain] Consider adding neutral hcom

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/redtt#24]
It is strange that in our semantic domain we have "non-neutral" values that inhabit neutral semantic types. Nothing seems broken, but it doesn't seem right either. A solution is to have `ncom` and `ncoe` (for "neutral" composition and coercion), analogous to `fcom`.

**Comment by favonia** [comment]
I think it is time to consider this for `succ (winding l)`.

**Comment by jonsterling** [comment]
Let's theorize it then!

**Comment by favonia** [comment]
I would like to reopen this because I was also thinking about
```
  NHCom' : {dir : dir; ty : neu; cap : value; sys : comp_sys} -> neu
```

**Comment by favonia** [comment]
And we probably also need a neutral coe whose type is a `neu`? I wonder how `cubicaltt` did this.

**Comment by jonsterling** [comment]
Oh right, I see what you mean.

**Comment by jonsterling** [comment]
Related to: #193
