### ISSUE TITLE
Grammar wishlist

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/redtt#243]
Here's some things I'd like to change about the grammar, if we could find a way to parse them unambiguously:

- [x] don't require `(x, y : A) -> B`, instead support `(x y : A) -> B`

- [x] right now, projection frames like `foo .0` don't bind as tightly as I would like, so I need a lot of weird parentheses. Not sure about this. Maybe we should just check with Agda does for its copatterns and match that (it may be that they do the same thing, I can't remember)

- [ ] top-level declarations written without `let`, as in cubicaltt

- [x] parentheses instead of angle brackets for tuples

- [x] support `foo bar -> B` instead of needing `(foo bar) -> B`

feel free to add more.

**Comment by favonia** [comment]
Cross-references: #158.

**Comment by favonia** [comment]
It seems almost everything is done. I actually like the keyword `let` because we have other commands (like normalize). Thoughts?

**Comment by jonsterling** [comment]
@favonia I don't feel strongly about `let`, so I'm fine with regarding this ticket closed. Thank you for applying your Thought to the grammar!
