### ISSUE TITLE
Rename everything that has to do with "restriction" 

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/redtt#244]
This name is so confusing!! Let me count the ways:

1. We have something currently called "co-restriction", which is basically `(r = r') -> A`; this should actually be called "restriction".

2. What is currently called restriction is, conceptually, the pretype of extensions of a partial element to a total element. But we can't use "extension" for this, that's already taken.

I have proposed calling it "boundary refinement" and "boundary refinement types". Other ideas are welcome.

/cc @ecavallo @mortberg @cangiuli

**Comment by ecavallo** [comment]
Do we need to distinguish between boundary refinement types and nullary extension pretypes?

**Comment by jonsterling** [comment]
@ecavallo That's a good point that I hadn't considered...

**Comment by jonsterling** [comment]
It might make sense to combine them. In that case, these can be called "extension pretype".
