### ISSUE TITLE
Implement better PropIsEquiv

### ISSUE THREAD

**Issue by mortberg** [RedPRL/redtt#246]
One problem I had in cubicaltt was that the normal form of the proof of PropIsEquiv: 

https://github.com/RedPRL/redtt/blob/master/example/univalence.red#L113

was huge and hence had to be made opaque in order to not blow up the typechecker. It seems like the same is true for redtt:

https://github.com/RedPRL/redtt/commit/b99bac4eb7a25956403afb6890bac69720e65b01#commitcomment-30139222

I ported a much more direct proof to yacctt from cubicaltt:

https://github.com/mortberg/yacctt/commit/dd238a28f4710485cfc3a399f7ed3fea48239ef1#diff-4597bedd84ee09b2a30c44d58082463bR279

Note that I'm doing an hcom in Fiber which probably can be "simplified" even further:

https://github.com/mortberg/yacctt/commit/dd238a28f4710485cfc3a399f7ed3fea48239ef1#diff-4597bedd84ee09b2a30c44d58082463bL293

The normal form of these proofs are *much* smaller and they compute a lot better and there is probably no need to make them opaque during TC. However I conjecture that something like Evan's recent connection trick can be used to find an even simpler proof in redtt.

**Comment by jonsterling** [comment]
Nice!  Let's try it!
