### ISSUE TITLE
V-types puzzle

### ISSUE THREAD

**Issue by mortberg** [RedPRL/redtt#249]
A while ago I asked whether we can prove the following fact about V-types:
```
goal (A : U) : Path (Path U A A) (<i> V i A A (idEquiv A)) (<_> A) =
```

A solution was proposed by Jon using a connection: https://github.com/RedPRL/redtt/blob/master/example/univalence.red#L246

This is essentially `<j i> V (i /\ j) A A (idEquiv A)` which gives us a path with the right endpoints (except it's reversed), but @favonia pointed out to me just now that this is not a path over refl as desired in the original formulation of the puzzle. So the puzzle is still open. 

This puzzle is interesting as it is part of the definition of the Hopf fibration for S^2 defined as a 2-HIT. This is the part of the computation of Brunerie's number where I'm stuck so we will need to figure out how to solve the puzzle (or circumvent it) at some point if we want to try my problem in redtt.

For reference, here's the proof in cubicaltt: https://github.com/mortberg/cubicaltt/blob/pi4s3/examples/problem.ctt#L288

Note that it uses a 2-d Glue type... This is something that I cannot see how to do directly using V-types.

**Comment by ecavallo** [comment]
I have been thinking about this problem myself! I'm beginning to suspect that it is not true, but that we can construct an "improved" V which has this property à la http://www.cs.bham.ac.uk/~mhe/agda-new/Lumsdaine.html.

**Comment by favonia** [comment]
@ecavallo This should be true, because two paths give the same coercion operation, and by the full univalence two paths are identified. @mortberg did not like my solution (and hence this remains open) because a direct implementation of this idea would result in a long proof. I did not spend any nanosecond to optimize this yet.

**Comment by ecavallo** [comment]
Ah, good point...
