### ISSUE TITLE
Codes, HITs, and composition

### ISSUE THREAD

**Issue by ecavallo** [RedPRL/redtt#253]
```
import path
import unit

data O where
| obase
| oloop (y : O) @ i
  [ i=0 ⇒ y
  | i=1 ⇒ y
  ]

let Code (a : unit) : type =
  elim a [ triv ⇒ O ]

let encode (p : Path unit triv triv) : O =
  coe 0 1 obase in λ i → Code (p i)

let decode (o : O) : Path unit triv triv =
  elim o [
  | obase ⇒ λ _ → triv
  | oloop (o' ⇒ decode/o') i ⇒ λ j →
    comp 0 1 (decode/o' j) [
    | i=0 ⇒ λ _ → decode/o' j
    | i=1 ⇒ λ _ → decode/o' j
    | j=0 ⇒ λ _ → triv
    | j=1 ⇒ λ _ → triv
    ]
  ]

let test (o : O) (i : dim)
  : Path O (encode (decode (oloop o i))) (oloop o i)
  =
  ?
```
raises `Failure("equate_dim: dimensions did not match")`. The error disappears if I delete the boundary of `oloop`, replace it with something non-recursive, redefine `Code` as just `O`, or replace the composition in `decode` with just `decode/o' j`.

**Comment by jonsterling** [comment]
We've been having the same error message in some examples from @mortberg, thanks for this further example! I have been having a lot of trouble tracking down the problem, but for the example that I had before, what appeared to be happening was that `quote_nf` was being called, and then somehow in one of the recursive calls to `equate`, the left and right hand sides ceased to be equal (even though the initial call is putting the *same* thing on the left and right). In particular, a dimension was getting fucked up.

**Comment by jonsterling** [comment]
Here's an even simpler version:

```
data O where
| obase @ i []

let encode_ty (p : Path unit triv triv) (i : dim) : type =
  elim (p i) [ triv ⇒ O ]

let decode (o : O) : Path unit triv triv =
  elim o [
  | obase i ⇒ λ j →
    comp 0 1 triv [
    | j=0 ⇒ λ c → triv
    | j=1 ⇒ λ d → triv
    | i=0 ⇒ λ _ → ?
    ]
  ]

let bad-ty (o : O) (k : dim) : _ =
  coe 0 1 (obase 0) in encode_ty (decode (obase k))

normalize bad-ty

```

the last call fails

**Comment by ecavallo** [comment]
Not sure if this is related, but
```
data O where
| obase @ i []

let encode_ty (p : dim → unit) (i : dim) : type =
  elim (p i) [ triv ⇒ O ]

let decode (o : O) : dim → unit = 
  elim o [
  | obase i ⇒ λ j →
    comp 0 1 triv [
    | i=0 ⇒ λ _ → triv
    | i=1 ⇒ λ _ → triv
    ]
  ]

let bad-ty (o : O) (k : dim) : _ =
  coe 0 1 (obase 0) in encode_ty (decode (obase k))
```
raises `Failure("Datatype not found: obase")`, whereas
```
data O where
| obase @ i []

let encode_ty (p : dim → unit) (i : dim) : type =
  elim (p i) [ triv ⇒ O ]

let decode (o : O) : dim → unit = 
  elim o [
  | obase i ⇒ λ j →
    comp 0 1 triv [
    | j=0 ⇒ λ _ → triv
    | j=1 ⇒ λ _ → triv
    ]
  ]

let bad-ty (o : O) (k : dim) : _ =
  coe 0 1 (obase 0) in encode_ty (decode (obase k))
```
(with the system changed from `i=0`&`i=1` to `j=0`&`j=1`) passes.

**Comment by ecavallo** [comment]
Deleting previous comment, my mistake...

**Comment by ecavallo** [comment]
Now with #266 merged, if I try printing out `el0` and `el1` at the start of each `equate` I get a `TooMortal` at some point from an `NCoeAtType`.

**Comment by jonsterling** [comment]
Huh... I'll look into it. It might need to be reverted then, or it is indicating another bug. Thanks!

**Comment by ecavallo** [comment]
I'm guessing it's related to the existing bug, since it stops happening if I fill in the `?` with `triv`. (I forgot to say, this is with your most recent example.)

**Comment by jonsterling** [comment]
Booyah!!
