### ISSUE TITLE
OCaml 4.06.0+ already has ListUtl.tabulate

### ISSUE THREAD

**Issue by favonia** [RedPRL/redtt#282]
It is called `List.init`: https://caml.inria.fr/pub/docs/manual-ocaml/libref/List.html#VALinit

**Comment by jonsterling** [comment]
oh! Cool. Thanks! Let's use it.

**Comment by favonia** [comment]
@jonsterling The current travis will not be happy.

**Comment by jonsterling** [comment]
@favonia can you explain what you mean by that?

**Comment by favonia** [comment]
The OCaml on travis is too old.

**Comment by jonsterling** [comment]
@favonia ??? I was manually installing the correct version in the travis script. So I don't understand what you're talking about. Or did I install the wrong version in the script?

**Comment by jonsterling** [comment]
@favonia Weird, I am surprised anything worked at all before then (???). Thanks for fixing!
