### ISSUE TITLE
call for proposals on comment syntax

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/redtt#303]
I want to switch the comment syntax to something different. We stated with `;` because the original notation was lisp-like, but the lisp-style notation now appears only in the core language and not in the external language.

We need both line comments and block comments. In RedPRL, we used `//` for line comments, and I think we used `/* */` for block comments (can't remember). Personally, I liked `//` as it was easy to type, and I am less crazy about `/* */` because I felt it was a little ugly.

As a datapoint, lean uses `/- -/` for block comments, and it looks alright.

Open to any proposals!

**Comment by favonia** [comment]
Should `foo//` and `bar/*` be valid identifiers in your mind?

**Comment by jonsterling** [comment]
@favonia Hahaha, @cangiuli what do you think? :sunglasses:

**Comment by jonsterling** [comment]
(For context, this was a brutal power move that I accidentally unleashed against @cangiuli last time. I'll let him decide.)

**Comment by cangiuli** [comment]
I would prefer that `foo//` not be a valid identifier (but instead `foo` followed by a comment). I was very owned by the opposite behavior in RedPRL...

**Comment by jonsterling** [comment]
Carlo and I discussed it and to start, we will try the version where `--` can appear in an identifier. This is consistent with Agda-style lexing, which we have already kind of adopted.

**Comment by jonsterling** [comment]
(But it's still open for debate)

**Comment by jonsterling** [comment]
Closing this ticket for now, but debate and new proposals are still welcome.
