### ISSUE TITLE
elim boundary calculated incorrectly

### ISSUE THREAD

**Issue by ecavallo** [RedPRL/redtt#309]
```
data void where

data cool where
| one [v : void] 
| two [v : void] (a : cool) @ i [ i=0 → one v | i=1 → a ]

let test (a : cool) : void =
  elim a [
  | one v → v
  | two v (a' → v') i → ?
  ]
```
results in a hole with the restrictions `i = 0 ⇒ a'` and `i = 1 ⇒ v'`, but the `i = 0` face should actually be `v`.

**Comment by jonsterling** [comment]
Thank you for reporting this! I am a little busy over the next couple days, so if you wanted to investigate in the meanwhile, that would be welcome (as a first cut to suss out any logic errors, try checking `tac_elim` in `Refiner`). Alternatively, I can get to this in a bit.

**Comment by jonsterling** [comment]
I've started debugging in this branch: https://github.com/RedPRL/redtt/compare/issue-309

**Comment by jonsterling** [comment]
I think I found the problem.
