### ISSUE TITLE
elim does not instantiate the types in the context that depend on the eliminated variable

### ISSUE THREAD

**Issue by favonia** [RedPRL/redtt#316]
**EDIT: actually, the following idea is probably not okay. I was confused.**

---

Consider the following:
```
import unit
import void
import bool

let test (x : bool) : type =
  elim x [
  | tt → unit
  | ff → void
  ]

let test2 (x : bool) (y : test x) : type =
  elim x [
  | tt → ?
  | ff → ?
  ]
```
The `x` in the type of `y` should be instantiated with `tt` or `ff`. In this special case I could delay the lambda abstraction, but it seems there are cases where I have to do the lambda abstraction first.

**Comment by favonia** [comment]
This is not a correct idea until we implement the correct elaboration algorithm.

**Comment by jonsterling** [comment]
@favonia What do you mean by the "correct elaboration algorithm"? The behavior observed in here is correct already.

**Comment by favonia** [comment]
@jonsterling Sorry, I meant the Immortal elaboration for **pattern matching.**

**Comment by jonsterling** [comment]
@favonia Ah cool! yeah, eventually we will want to automatically generalize the goal. I think that will be Stage 2 of N for pattern matching.
