### ISSUE TITLE
Non-local validity

### ISSUE THREAD

**Issue by favonia** [RedPRL/redtt#330]
The following should be valid, but it requires non-local reasoning:
```
comp x 1 blah [x=0 -> refl | z=0 -> \ y -> comp x y bar [x=0 -> refl]]
```
This can be done with a separate context to determine validity. The idea is to check the validity of the inner `hcom` under the substitution `1/y`.

**Comment by favonia** [comment]
#270 is blocking this.

**Comment by jonsterling** [comment]
Can we update this ticket with the new Thought? I can't remember what we determined, but it involved the fact that it might be a little too naive to work.

**Comment by favonia** [comment]
I did not have the time to work out the full story yet. I do not really trust the ideas until I go through the Kan operations of universes.
