### ISSUE TITLE
System rectification campaign

### ISSUE THREAD

**Issue by favonia** [RedPRL/redtt#331]
All of these should be implemented. This applies to compositions, extention types, and boundaries of constructors. @jonsterling @cangiuli @ecavallo

- [ ] False removal: remove any false faces as soon as possible.
- [ ] Remove false faces from boundary refinements in elaborator
- [ ] True dominance: identify `0=0`, `1=1` and `x=x` with just `True`, and any coherent valid system with a true face is identified with a system with only that true face.
- [ ] Constant symmetry: identify `r=0/1` and `0/1=r` with maybe `Eq0 r` or `Eq1 r`
- [ ] Duplicate removal: only keep the first (left-most) copy in a system.

**Comment by jonsterling** [comment]
@favonia Can you give a bit more detail about the level of generality you'd like to see?

**Comment by favonia** [comment]
@jonsterling If we want to use types to enforce abstraction, rigid systems are of some abstract type, like `Eq.t` or `Dir.t`. Clients do not even know they are lists.

**Comment by jonsterling** [comment]
The "true dominance" one is a great idea!

**Comment by favonia** [comment]
Spiritually done in https://github.com/RedPRL/kado.
