### ISSUE TITLE
Use Fst/Snd instead of Car/Cdr in the core language

### ISSUE THREAD

**Issue by favonia** [RedPRL/redtt#342]
Just to make the output less confusing to others.

**Comment by jonsterling** [comment]
@favonia In the pretty printer? I didn't realize I hadn't fixed that :laughing:

**Comment by favonia** [comment]
@jonsterling No, I meant *everywhere*. Consider this as a clean-up.

**Comment by jonsterling** [comment]
Ah!! Yes, I support this.

**Comment by jozefg** [comment]
No! How will we know which registers the fst and snd projection will live in on old machines?! Please keep redtt close to the metal.
