### ISSUE TITLE
Consider adding a new class for volatile terms in addition to commands and constructors

### ISSUE THREAD

**Issue by favonia** [RedPRL/redtt#345]
This class includes the "contsructors" for `V` types, `fhcom` types, and maybe more in the future.

One of the invariants is that a *volatile* term can always synthesize the most general type, and thus checking them is always done by synthesizing the most general type first in a bidirectional type checking. They differ from the commands because sometimes they themselves behave like constructors. They differ from usual constructors because the head symbol might change. The additional requirement is then a volatile term needs to synthesize some reasonable type by itself. @jonsterling

**Comment by jonsterling** [comment]
We will have to determine whether we want a mix of checking and synthesis, or just synthesis... I wonder if it makes a difference.

**Comment by jonsterling** [comment]
Based on discussion with @cangiuli  and @ecavallo today I want to again suggest the following alternative:

In the implementation, *don't* add all these annotations, and just do the untyped reduction. How is this justified? We would just prevent the user from ever writing down a non-rigid V/VIn/VProj/box term. Then, we would have the invariant that these only ever come from well-typed rigid ones, as their substitution instances. 

This would be simpler for now, at least until we determine (on paper) the immortal version. What do you think?

**Comment by favonia** [comment]
> We would just prevent the user from ever writing down a non-rigid V/VIn/VProj/box term.

I am not sure if this would work in all cases. We probably want to at least change `check_tm_sys` because some rigid terms may become non-rigid under double restrictions when checking adjacency constraints.

**Comment by jonsterling** [comment]
Hmm... I'm not sure why check_tm_sys needs to change.

**Comment by favonia** [comment]
@jonsterling Sorry, you are right. I forgot you already use `Cx.eval` there.
