### ISSUE TITLE
Let equate_ty (quote_ty, equiv_ty) handle the types directly

### ISSUE THREAD

**Issue by favonia** [RedPRL/redtt#363]
This WILL be done in #270 unless @jonsterling says no.

**Comment by jonsterling** [comment]
@favonia Is the idea to have a separate quotation function for types, rather than piggy-backing on the universe? Or something else?

**Comment by favonia** [comment]
> Is the idea to have a separate quotation function for types

Yes. It is `equate` calling `equate_ty` for elements in the universes, not the other way around.
