### ISSUE TITLE
Proposal for better HIT declaration notation

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/redtt#368]
Parametric HITs are written as follows:

```
data F (x : A) where
| con (y : B) (r : F) ...
...
```

This notation is not great for a couple reasons:

1. Conceptually it makes sense that the recursive arguments are called `foo` only and not `foo A`, but it may be confusing to a user who doesn't have in mind a schema, but is just thinking about programming.

2. How will we distinguish *indices* from parameters? There's some options, but all of them are kind of confusing.

I have an idea that should resolve both issues at once. Below is my proposed notation for parametric & indexed HITs:

```
(x : A) ⊢ data F (ix : I) ... where
| con (y : B) (r : F i) ...
...
```

We would unleash the fragment of this notation for parametric HITs first. The only problem is that there is no vim digraph for the turnstile, but I bet it is possible to add one in the vim mode (@cangiuli?). In fact, we should actually consider making the vim mode auto-replace various symbols with their immortal/unicode equivalents as you type, so users don't have to learn digraphs.

I have a related proposal for a very immortal notation to define functions by case/elimination trees in the style of Epigram.

/cc @favonia

**Comment by favonia** [comment]
How about Agda's solution? I wish we can also specify the kind (which might affect the Kan operations).
```
data F (x : params) : indices -> U discrete 0 where
```

**Comment by jonsterling** [comment]
@favonia I don't like Agda's solution, and moreover, the "parameters" in Agda actually behave completely different from how parameters work in our setting. They are like a cross between indices and parameters.

FYI, you can already specify the kind in redtt:

```
 data foo : type kan
...
```

**Comment by jonsterling** [comment]
In fact, it would be cool to have Agda-style parameters too. In that case, the immortal notation would be:

```
data <real parameters> !- foo <agda-parameters> : <indices> -> type kind
```
