### ISSUE TITLE
redtt aborts on macOS

### ISSUE THREAD

**Issue by UlrikBuchholtz** [RedPRL/redtt#387]
When I run `redtt` I get (at commit ffdfa9a8006e7529c6ee3ad832a0b3b776848f15):

    $ redtt
    dyld: __dyld section not supported in /Users/ulrikbu/.opam/4.07.0/bin/redtt
    Abort trap: 6

More information about my system (an iMac from the University of Oslo running Mojave):

    $ uname -a
    Darwin foobar.uio.no 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64
    $ g++ --version
    Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
    Apple LLVM version 10.0.0 (clang-1000.10.44.2)
    Target: x86_64-apple-darwin18.0.0
    Thread model: posix
    InstalledDir: /Library/Developer/CommandLineTools/usr/bin
    $ opam config report
    # opam config report
    # opam-version      2.0.0
    # self-upgrade      no
    # system            arch=x86_64 os=macos os-distribution=macos os-version=10.14
    # solver            builtin-mccs+glpk
    # install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
    # upgrade-criteria  -removed,-count[version-lag,solution],-new
    # jobs              3
    # repositories      1 (http) (default repo at d15c8592)
    # pinned            1 (git)
    # current-switch    4.07.0
    $ opam list
    # Packages matching: installed
    # Name              # Installed  # Synopsis
    base-bigarray       base
    base-bytes          base         Bytes library distributed with the OCaml compiler
    base-threads        base
    base-unix           base
    biniou              1.2.0        Binary data format designed for speed, safety, ease of use and backward compatibility as protocols evolve
    camomile            1.0.1        A Unicode library
    cmdliner            1.0.2        Declarative definition of command line interfaces for OCaml
    conf-m4             1            Virtual package relying on m4
    conf-which          1            Virtual package relying on which
    cppo                1.6.5        Equivalent of the C preprocessor for OCaml programs
    dune                1.1.1        Fast, portable and opinionated build system
    easy-format         1.3.1        High-level and functional interface to the Format module of the OCaml standard library
    jbuilder            transition   This is a transition package, jbuilder is now named dune. Use the dune
    lambda-term         1.13         Terminal manipulation library for OCaml
    lwt                 4.1.0        Promises, concurrency, and parallelized I/O
    lwt_log             1.1.0        Lwt logging library (deprecated)
    lwt_react           1.1.1        Helpers for using React with Lwt
    menhir              20181006     LR(1) parser generator
    merlin              3.2.2        Installation with Opam
    ocaml               4.07.0       The OCaml compiler (virtual package)
    ocaml-base-compiler 4.07.0       Official release 4.07.0
    ocamlbuild          0.12.0       OCamlbuild is a build system with builtin rules to easily build most OCaml projects.
    ocamlfind           1.8.0        A library manager for OCaml
    ocp-build           1.99.20-beta Project builder for OCaml
    ocp-indent          1.6.1        A simple tool to indent OCaml programs
    react               1.2.1        Declarative events and signals for OCaml
    redtt               0.0          pinned to version 0.0 at git+file:///Users/ulrikbu/src/redtt#master
    result              1.3          Compatibility Result module
    topkg               0.9.1        The transitory OCaml software packager
    uchar               0.0.2        Compatibility library for OCaml's Uchar module
    utop                2.2.0        Universal toplevel for OCaml
    uucp                11.0.0       Unicode character properties for OCaml
    uuseg               11.0.0       Unicode text segmentation for OCaml
    uutf                1.0.1        Non-blocking streaming Unicode codec for OCaml
    yojson              1.4.1        Yojson is an optimized parsing and printing library for the JSON format
    zed                 1.6          Abstract engine for text edition in OCaml```

Let me know if you need more information!

**Comment by jonsterling** [comment]
Hi @UlrikBuchholtz, I'm sorry you experienced a problem running `redtt`! Based on my searching, I believe that this is a problem introduced by either macOS Mojave or the Xcode 10 development tools. I am seeing a flurry of forum posts over the past couple weeks referring to exactly this problem, for many things besides OCaml.

We'll see if there's any way that we can work around it on our end, but it is likely that this will have to be resolved on the side of the tool vendors.

**Comment by UlrikBuchholtz** [comment]
Thanks, @jonsterling – if there's anything I can do to help figure out which tool is responsible, let me know. For instance, I can get a working installation of coq via `opam install coq` on the same setup, so whatever is causing this issue is a difference between the tools used by coq and redtt.

**Comment by jonsterling** [comment]
I don't have access to a Mac right now to try and troubleshoot this issue, but let me just ask a few questions whose answers might be helpful to us:

Had you installed various OCaml libraries prior to upgrading to Mojave? Or is this a clean install?

The reason I am asking is, I believe that something changed about how this section is dealt with in Mojave's development tools, and it might be that if there are some libraries installed that were built with the old development tools, they may not be compatible anymore. If that's the case (that you have things installed which were built with the old ones), I wonder what would happen if you wiped them all out and tried installing everything again. (Please don't take this as a recommendation, since in the realm of linker issues, I am personally completely out of my depth.)

**Comment by UlrikBuchholtz** [comment]
This is a clean install of opam/ocaml on Mojave. I won't be back at the office with the machine until Monday, but then I'll be happy to try more experiments, including wiping opam and reinstalling with tweaked settings.

**Comment by UlrikBuchholtz** [comment]
By bisection I narrowed the issue to commit d3a0894110d0f8baefb51a03f0543d3caf716998 (turn on profiling). So the following “fix” suggested itself:

    diff --git a/src/bin/dune b/src/bin/dune
    index de61e55..53a8426 100644
    --- a/src/bin/dune
    +++ b/src/bin/dune
    @@ -1,6 +1,5 @@
     (executables
      (names main)
    - (ocamlopt_flags (:standard -p))
      (libraries cmdliner lwt.unix redtt))
    
     (install

And this indeed works! So the issue was the profiling option. I don't know enough to say what the best resolution is, though: Should profiling be disabled for all? Is this a bug in ocaml or is `-p` just not supported on mac? If it's a bug, where do I report it?

**Comment by jonsterling** [comment]
@UlrikBuchholtz  Oh wow! That's fascinating. Really good sleuthing. We will disable profiling on our end, and just use it manually when we need it.

It's hard for me to say whether this is an OCaml or a macOS bug, or neither, so I will first content myself with having a solution that lets Mac users build redtt :smile:
