### ISSUE TITLE
POSIX mount semantics [WIP]

### ISSUE THREAD

**Issue by favonia** [RedPRL/redtt#423]
This is after #418. The analogy is to treat the current file system as partitions on a disk, and we are building a virtual file system on top of them.

Axioms:

0. Each `redlib` file denotes the root of a virtual partition. Each actual file in a virtual partition is defined to be an actual relative path without `..` from the root. Symbolic links and others will not identify two files within a virtual partition.
1. There is no overlapping in actual files between two virtual partitions.
2. Each `redlib` file also denotes the root of a virtual file system, with the current virtual partition mounted at root and other virtual file systems mounted at different virtual path according to the `redlib` file.
3. Content in the same actual file will be identified, even if accessed through different virtual paths.

**Comment by cangiuli** [comment]
Can you elaborate on (3)? How does that situation arise?

**Comment by favonia** [comment]
@cangiuli Library A is mounting libraries B and C, and library B itself is also mounting library C.

**Comment by favonia** [comment]
Implemented by https://github.com/RedPRL/bantorra.
